# /srv/docker/linuxmuster-nginx-proxy/docker-compose.yml
#
# thomas@linuxmuster.net
# 20180310

version: '2'

services:
  linuxmuster-nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: linuxmuster-nginx-proxy
    @@ports@@
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/linuxmuster/ssl:/etc/nginx/certs:ro
      - ./conf.d:/etc/nginx/conf.d

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
